name: Deploy to Dokku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Décoder la clé privée
      - name: Decode SSH key
        run: |
          echo "${{ secrets.DOKKU_SSH_KEY }}" | base64 -d > dokku_key
          chmod 600 dokku_key

      # Étape 3 : Ajouter la clé privée à ssh-agent avec la passphrase
      - name: Add SSH key to agent with passphrase
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.DOKKU_SSH_KEY_BASE64 }}" | base64 -d > dokku_key
          chmod 600 dokku_key
          expect << EOF
          spawn ssh-add dokku_key
          expect "Enter passphrase for dokku_key:"
          send "${{ secrets.DOKKU_SSH_PASSPHRASE }}\r"
          expect eof
          EOF

      # Étape 4 : Ajouter l'hôte Dokku à known_hosts
      - name: Add Dokku host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DOKKU_HOST }} >> ~/.ssh/known_hosts

      # Étape 5 : Déployer avec Dokku
      - name: Deploy to Dokku
        run: git push dokku main:master

      # Étape 6 : Nettoyer la clé SSH
      - name: Cleanup SSH key
        run: rm dokku_key
