name: Auto-Deploy to Dokku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer SSH
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}
          ssh-passphrase: ${{ secrets.DOKKU_SSH_PASSPHRASE }}

      # Étape 3 : Ajouter le serveur Dokku à known_hosts
      - name: Add Dokku host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DOKKU_HOST }} >> ~/.ssh/known_hosts

      # Étape 4 : Déployer avec Dokku
      - name: Deploy to Dokku
        run: git push dokku main:master
